---
- name: Install virtualization packages and dependencies
  community.general.rpm_ostree_pkg:
    name:
      - virt-install
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvm
      - virt-manager
      - virt-viewer
    state: present
  when: ansible_facts['distribution'] == 'Silverblue'

- name: Install kali virtualization packages and dependencies
  apt:
    name:
      - qemu-system
      - libvirt-daemon-system
      - virt-manager
    state: present
  when: ansible_facts['distribution'] == "Kali"

- name: Create default libvirt network
  community.libvirt.virt_net:
    command: define
    name: default
    xml: '{{ lookup("template", "files/bridge.xml.j2") }}'

- name: Start and enable on-boot default network
  community.libvirt.virt_net: 
    command: start
    autostart: true
    name: default

- name: Create working directory
  file:
    path: "{{ WORKING_DIR }}"
    state: directory

- name: Extract downloaded file
  unarchive:
    src: "{{ WORKING_DIR }}/{{ WHONIX_ISO }}"
    dest: "{{ WORKING_DIR }}"

- name: Define whonix networks
  block:
    - name: Get whonix internal network file name path
      find: 
        path: "{{ WORKING_DIR }}"
        pattern: Whonix_internal*.xml
      register: whonix_internal_network

    - name: Assign whonix internal network file name to variable
      set_fact:
        whonix_internal_network_path: "{{ whonix_internal_network.files.0.path }}"

    - name: Rename internal virtual bridge
      replace:
        path: "{{ whonix_internal_network_path }}"
        regexp: "virbr2"
        replace: "virbr12"

    - name: Define whonix internal network
      community.libvirt.virt_net:
        command: define
        name: Whonix-Internal
        xml: "{{ lookup('template', '{{ whonix_internal_network_path }}') }}"

    - name: Start and enable on-boot whonix internal network
      community.libvirt.virt_net: 
        command: start
        autostart: true
        name: Whonix-Internal

    - name: Get whonix external netowrk file name path
      find: 
        path: "{{ WORKING_DIR }}"
        pattern: Whonix_external*.xml
      register: whonix_external_network

    - name: Assign whonix external network file name to variable
      set_fact:
        whonix_external_network_path: "{{ whonix_external_network.files.0.path }}"

    - name: Rename external virtual bridge
      replace:
        path: "{{ whonix_external_network_path }}"
        regexp: "virbr1"
        replace: "virbr11"

    - name: Define whonix external network
      community.libvirt.virt_net:
        command: define
        name: Whonix-External
        xml: "{{ lookup('template', '{{ whonix_external_network_path }}') }}"

    - name: Start and enable on-boot whonix external network
      community.libvirt.virt_net: 
        command: start
        autostart: true
        name: Whonix-External

- name: Define Whonix virtual machines
  block:
    - name: Get whonix gateway xml file name path
      find: 
        path: "{{ WORKING_DIR }}"
        pattern: Whonix-Gateway*.xml
      register: whonix_gateway_xml

    - name: Assign whonix gateway xml name to variable
      set_fact:
        whonix_gateway_xml_path: "{{ whonix_gateway_xml.files.0.path }}"

    - name: Define Whonix Gateway VM
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', '{{ whonix_gateway_xml_path }}') }}"

    - name: Get whonix workstation xml file name path
      find: 
        path: "{{ WORKING_DIR }}"
        pattern: Whonix-Workstation*.xml
      register: whonix_workstation_xml

    - name: Assign whonix workstation file name to variable
      set_fact:
        whonix_workstation_xml_path: "{{ whonix_workstation_xml.files.0.path }}"

    - name: Define Whonix Workstation VM
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', '{{ whonix_workstation_xml_path }}') }}"

- name: Check if whonix gateway image exists
  stat:
    path: /var/lib/libvirt/images/Whonix-Gateway.qcow2
  register: whonix_gateway_vm_exists

- name: Move Whonix Gateway image to libvirt image directory
  block:
    - name: Get whonix gateway image file name path
      find: 
        path: "{{ WORKING_DIR }}"
        pattern: Whonix-Gateway*.qcow2
      register: whonix_gateway_vm

    - name: Assign whonix gateway image file name to variable
      set_fact:
        whonix_gateway_vm_path: "{{ whonix_gateway_vm.files.0.path }}"

    - name: Copy Whonix gateway image to /var/lib/libvirt/images
      copy:
        src: "{{ whonix_gateway_vm_path }}" 
        dest: /var/lib/libvirt/images/Whonix-Gateway.qcow2
  when: not whonix_gateway_vm_exists.stat.exists

- name: Check if whonix workstation image path exists
  stat:
    path: /var/lib/libvirt/images/Whonix-Workstation.qcow2
  register: whonix_workstation_vm_exists

- name: Move Whonix Workstation image to libvirt image directory
  block:
    - name: Get whonix workstation image file name path
      find: 
        path: "{{ WORKING_DIR }}"
        pattern: Whonix-Workstation*.qcow2
      register: whonix_workstation_vm

    - name: Assign whonix workstation image file name to variable
      set_fact:
        whonix_workstation_vm_path: "{{ whonix_workstation_vm.files.0.path }}"

    - name: Move Whonix workstation image to /var/lib/libvirt/images
      copy:
        src: "{{ whonix_workstation_vm_path }}" 
        dest: /var/lib/libvirt/images/Whonix-Workstation.qcow2
  when: not whonix_workstation_vm_exists.stat.exists
